# conda environment description file for HueBot package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f HueBot/env/environment-dev.yaml
#   $ source activate huebot
#   (huebot)$ pip install --editable HueBot
#
# See the env/requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: huebot

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python=3.7

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme
